---
abstract: 'Services for Bot::Backbone optimized for fun'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bot-Backbone-Service-OFun
requires:
  Acme::Scurvy::Whoreson::BilgeRat: '0'
  Bot::Backbone: '0'
  Bot::Backbone::Service: '0'
  Bot::Backbone::Service::Role::Responder: '0'
  Bot::Backbone::Service::Role::Service: '0'
  Bot::Backbone::Service::Role::Storage: '0'
  Digest::SHA: '0'
  File::Slurp: '0'
  Hailo: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  MooseX::Types::Path::Class: '0'
  Readonly: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Bot-Backbone-Service-OFun
  repository: git://github.com/zostay/Bot-Backbone-Service-OFun.git
version: '0.142230'
